#!/bin/bash
echo "============================================"
echo "  Scenario 2: Modification Detected"
echo "============================================"
echo ""
echo "This scenario requires manual intervention:"
echo ""
echo "  1. Go to the Slack channel #incident-2026"
echo "  2. Find the most recent ciphertext blob"
echo "  3. Edit one character in the 'ciphertext' field"
echo "     (e.g., change a letter from 'A' to 'B')"
echo "  4. Then run the fetch command below"
echo ""
echo "Command to run after tampering:"
echo "  python client.py fetch --channel incident-2026 --receiver bob"
echo ""
echo "Expected output:"
echo "  [TAMPER] Decryption failed for message from alice"
echo "           seq=N -- message modified or wrong key"
echo ""
echo "============================================"
echo "  Why this works: AES-256-GCM produces a"
echo "  16-byte authentication tag computed over"
echo "  both the ciphertext and the AAD. ANY"
echo "  modification to either invalidates the tag."
echo "============================================"
